inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2

# Notify uses address_line_1 etc naming convention and we want to align with it
Naming/VariableNumber:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false
