inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml

require:
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2

# Notify uses address_line_1 etc naming convention and we want to align with it
Naming/VariableNumber:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true
  AllowedCops:
    - Layout/LineLength
    - Metrics/BlockLength
    - Metrics/ClassLength
    - Metrics/MethodLength
    - Metrics/ModuleLength
    - Naming/MemoizedInstanceVariableName
    - RSpec/AnyInstance
    - RSpec/LetSetup
    - Style/EmptyElse
    - Style/ExplicitBlockArgument
