dist: trusty

addons:
  sonarcloud:
    organization: "defra"

language: ruby
rvm: 2.7.1
cache: bundler

# Travis CI uses shallow clone to speed up build times, but a truncated SCM
# history may cause issues when SonarCloud computes blame data. To avoid this,
# you can access the full SCM history with `depth: false`
git:
  depth: false

env:
  global:
    - WCRS_REGISTRATION_EXPIRES_AFTER=3
    - WCRS_REGISTRATION_RENEWAL_WINDOW=3
    - WCRS_REGISTRATION_GRACE_WINDOW=5
    - WCRS_RENEWAL_CHARGE=10500
    - WCRS_NEW_REGISTRATION_CHARGE=15400
    - WCRS_TYPE_CHANGE_CHARGE=4000
    - WCRS_CARD_CHARGE=500
    - WCRS_USE_AIRBRAKE=true
    # Just used to make the tests pass
    - WCRS_WORLDPAY_ECOM_USERNAME=foo
    - WCRS_WORLDPAY_ECOM_PASSWORD=foo
    - WCRS_USE_XVFB_FOR_WICKEDPDF=true
    - ENV_VARIABLE_TEST_FEATURE=true
    - secure: o9U2sDP6gXdghm5OZ6IiYSrTX9PZ0D/73yfTpQQnRdN9F/GTIY/bn1a9TVuJu3b/zljRo2ComoMrKAAoRx4qJeXuIef5YbB75p8/6iOP16KWfrECQjDEny1z5qWBHQxXmZvJvYNP6dkh2r89mw7IX+veVPny8XJcVU/0twIQBFp7LEp/Tun0fSUfxZ4USSNJqEs4wEaoxHvO7LFT85/C5PbGNr6gz+3MWEFUiQcYixG0XlYOhou0UDKcySBnkPyT89HtJbJxu+nYTAtbjhMBjsgBpIvhGIG0FQT0HL8oRIcdurC2PyEobyxjOaitvOfE4dE8RuAEeeNuwaCFhtESq2JcgYzaB1f4bbLz/qQ1ox7rx6esjnrKBmZZgRR6WU0RIzQkq/kXpRyR1yFO27cLN0g8PbdA7gjHYJw6Iz4hJlL4N5S86x3JPWfJKGdyNnKKGrohTVSm28BHQ69ndgWN4+he3o8bD/vKL9sTVCnjYw1W+Kh1FKm7ZjqTaAJNbKeMCKZ5B4A1ROs7GbVVH/OVdP+HnxgEGPL+svYUk5A2IDTO6ULkImGK/PEJQgNEEjYu0+hG3h4enFB+MSOEPpMEgfhg6Pwnn7rg8JtvlSCMQe6oyAJYFABYWIZK5BMsaL1otzNyXsoYcNjKxyMt2wwwitZ1cLiOFjDiJvaALuEW9mw=
    - secure: qFVA9FtuLwcgXF+Tsml8bIvBDxQqC43adOterkZBQXvKWVvr/I+OfgW1enQLQla7ewVFsreKBNqV5Hdh6icsIIebsktD663Uixmci0oewwfmpZNLdBNe7qSXHW6OLNS6N13vf6K3GhEkAG+TY+KLWRj9XPNdfY60PXAqqQonOZ24Bm9ONX95j1HZ31JHv9E5VUh90f9grMt8A+8JMVWHNQ3qSiOGEduvnOA4yG2Wsc37Uc7fflrKvx1IZTIkLQ+a6agxOglbr2hyyEKXjhzr1gj4TToueE+yL+c6IXFfir/JZwwq36u8Pv9o2nh4g4s9OZRFLzVGeeeV9dl+pDl8rmJjte9aG4KbdWpHvXkQhLxaIJndmc47nv2KDfDdeASWU9y+CQ1WFckj2e3o1HIht5AXtxvW7/B5OYYQb1ukXxJQJVpMOr7qJxF8e8DyYImXp3lcBuf/d1wlInZiyOpfFo5WyKqGxyuYVWH2dbNcCYCj5TmzsFNO1PA9QeYgFWYPReJXDa5L8PUD6ckzNdxYH3PIo0xC+ynLlcXKBT3EoCe9z0bK4rAM4y9pxZz5Bk4qTm2BkV/g/fbnG1AhmVI06zZDR/l430u95G2/4UubNX/oeYSKbFAAWIM1C2WdBbNJ+yNRzjxlIRnKnV00uU3xenKb+ZRSlEA+ikKFglDOv5Q=
    - secure: vXVEG464kqUt8qfOVhaHtZ9xEt1aZMYGLTmCBNnmxJ4HpzXWdWMztg6u4VTISap3RE9us8zQLX4ql6F6Az2pPddoIWWuHP4grCN6iUqGfsK1BhxkLf/gE4R7mxLsJorQFWz9z618H2Z0vZkRGxDDCrUOX6hL5EOK6VwWUufNBHr6Z6d6+J7ggtz+r9wQ97JHxHggIzoy4FLVcR9o5qWYWpTH2v0EW49l9n+Dm7FfPzu1nwJBLpDQX2uBTNxfaiuDjx3iNrmYa8NkqDLKErwB8CeISqbzpJ3OBgqwZR5+jtJXOMEzUkwV8HC3xPkedqcqZ7YwZk4zkcPoD6qMvGKL56DOJHK5wInXllo5EA+xnMzPdVysl9sTesfFgwQga6V9UwZuSNf8TuV7sA93p4HZLLwCw7u6PWuIlcMCOZ9qAJbervq6ZkPGi/VwO8Z+0XnRMaEqTo0H69imJNqT5Nsbjz5SLDeRnPHzWZ2R+PZ/yCF95ZDszPWKSLjtXuMs91h0OZjCIuFcoVZDLx+vT9lvrgG8qN0w0xGIpzaWLQiu9vSkDAzKeWdOmqPbrghgVd7A32mT8XkOiRR3L2NWMFcPmGgsIhmka0SK6mdvPZQ2hS3B0jrmxg0x3Ax+qfi8W6G7Z5hmEkk19NmlXpYqrfbSzSJ2Qvedx+rKSILXS+XzS9g=
  matrix:
    secure: Kcymo4dlw9/N7roosBvEvIzhpTSWhvQwzrL6iWowBNsdsQ/H3o+MBQteoL0rYtJVche3sRVhmqXo5YIQ8CUk5oYD8S4oFwWSMODe6XnO/odBsDC3mtzc8YCILVMsnni504KDxxSz7Zl3SZ0JbAyUGNBi1HQ3EuXylvCv3QnDE20UcUvb+OpilqgDzsjFaOb/FKEgUZuXF8TisiCtpU3CR7HFV/Fw37cYvtHK5mUNNTmW88laTvR3l2eel3SRIl8PUUWWyRgtu7h2n4gq3cbV9SIs/AgDEEvGkVhsWgK2l6yPbGtMVWjVihbo71KX0ec0yTxliD8WTvlao6R7Iwagp/jg11evJMYUVx+1GkLGfxzZcVmIOwYdNFcVROPBAB8TVbbd+wdO8W93tVHEnDHQBM6Ol2qxCC0RNWi3ElD2Sg6rx34ECEhlK8tWoyZTHTlWGz32ctt6fNftJOPM0euQhLpr7ZBz7GqfJMYy5+tCm110SmLXvxe5cotoIofJ29U2DkZACa0sSPkQSnco/xA0aYXOL1fPCPFyRwmN8wXBMxZi6SeGtC47Zg5I2e447zinvv+4hsMlwESiwvCMGEGBmBIKuMg5Nqk0o3lPE4bfRiDkAiHOrLAhhUBQxM4sE5wyg81jr172E1gDVgSAU1hkCyRGObqzaDaH/cybOc397ic=

services:
  - mongodb

before_install:
  - export TZ=UTC
  - gem install bundler
  - sudo apt-get install xvfb -y
  - sudo apt-get install ttf-liberation -y
  - sudo apt-get install wkhtmltopdf -y

before_script:
  # Set up Mongo databases
  - mongo waste-carriers-test --eval 'db.createUser({user:"mongoUser", pwd:"password1234", roles:["readWrite", "dbAdmin", "userAdmin"]})'
  - mongo waste-carriers-users-test --eval 'db.createUser({user:"mongoUser", pwd:"password1234", roles:["readWrite", "dbAdmin", "userAdmin"]})'

script:
  - bundle exec rubocop --format progress --format json --out rubocop-result.json
  - bundle exec rspec
  - sonar-scanner
